export interface TMDBLanguageOption {
  code: string;
  label: string;
}

export const TMDB_LANGUAGES: TMDBLanguageOption[] = [
  { code: "en-US", label: "English (US)" },
  { code: "en-GB", label: "English (UK)" },
  { code: "it-IT", label: "Italiano" },
  { code: "tr-TR", label: "Türkçe" },
  { code: "fr-FR", label: "Français" },
  { code: "de-DE", label: "Deutsch" },
  { code: "es-ES", label: "Español (España)" },
  { code: "es-MX", label: "Español (México)" },
  { code: "pt-BR", label: "Português (Brasil)" },
  { code: "pt-PT", label: "Português (Portugal)" },
  { code: "nl-NL", label: "Nederlands" },
  { code: "pl-PL", label: "Polski" },
  { code: "ru-RU", label: "Русский" },
  { code: "uk-UA", label: "Українська" },
  { code: "sv-SE", label: "Svenska" },
  { code: "no-NO", label: "Norsk" },
  { code: "da-DK", label: "Dansk" },
  { code: "fi-FI", label: "Suomi" },
  { code: "el-GR", label: "Ελληνικά" },
  { code: "cs-CZ", label: "Čeština" },
  { code: "sk-SK", label: "Slovenčina" },
  { code: "hu-HU", label: "Magyar" },
  { code: "ro-RO", label: "Română" },
  { code: "bg-BG", label: "Български" },
  { code: "hr-HR", label: "Hrvatski" },
  { code: "sr-RS", label: "Српски" },
  { code: "sl-SI", label: "Slovenščina" },
  { code: "lt-LT", label: "Lietuvių" },
  { code: "lv-LV", label: "Latviešu" },
  { code: "et-EE", label: "Eesti" },
  { code: "ja-JP", label: "日本語" },
  { code: "ko-KR", label: "한국어" },
  { code: "zh-CN", label: "中文 (简体)" },
  { code: "zh-TW", label: "中文 (繁體)" },
  { code: "zh-HK", label: "中文 (香港)" },
  { code: "hi-IN", label: "हिन्दी" },
  { code: "th-TH", label: "ไทย" },
  { code: "vi-VN", label: "Tiếng Việt" },
  { code: "id-ID", label: "Bahasa Indonesia" },
  { code: "ms-MY", label: "Bahasa Melayu" },
  { code: "ar-SA", label: "العربية" },
  { code: "fa-IR", label: "فارسی" },
  { code: "ur-PK", label: "اردو" },
  { code: "bn-BD", label: "বাংলা" },
  { code: "ta-IN", label: "தமிழ்" },
  { code: "te-IN", label: "తెలుగు" },
  { code: "ka-GE", label: "ქართული" },
  { code: "az-AZ", label: "Azərbaycan" },
  { code: "hy-AM", label: "Հայերեն" },
  { code: "fil-PH", label: "Filipino" },
  { code: "sw-KE", label: "Kiswahili" },
  { code: "af-ZA", label: "Afrikaans" },
  { code: "ca-ES", label: "Català" },
  { code: "eu-ES", label: "Euskara" },
  { code: "gl-ES", label: "Galego" },
  { code: "is-IS", label: "Íslenska" },
  { code: "ga-IE", label: "Gaeilge" },
  { code: "cy-GB", label: "Cymraeg" },
];

export function isKnownTmdbLanguage(code: string): boolean {
  return TMDB_LANGUAGES.some((l) => l.code === code);
}
